application: learn-2-code
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  #application_readable: true
- url: /images
  static_dir: images
  #application_readable: true
- url: /templates
  static_dir: html_templates
  application_readable: true
- url: /.*
  script: notes.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest